// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/.svn/text-base/Marker.svn-base>
#include <osgART/ARTTransformCallback>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(osgART::ARTTransformCallback)
	I_Constructor1(IN, osgART::Marker *, marker);
	I_Constructor1(IN, osgART::Marker *, marker);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgART::ARTTransformCallback)
	I_Constructor1(IN, osgART::Marker *, marker);
	I_Constructor1(IN, osgART::Marker *, marker);
END_REFLECTOR

