// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/ARTTransform>
#include <osgART/Marker>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgART::ARTTransform)
	I_ConstructorWithDefaults2(IN, int, markerID, 0, IN, int, trackerId, 0);
	I_Method0(osgART::Marker *, getMarker);
	I_ReadOnlyProperty(osgART::Marker *, Marker);
END_REFLECTOR

