// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/Field>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgART::Field)
	I_Constructor0();
	I_Method1(void, serialize, IN, std::ostream &, out);
END_REFLECTOR

TYPE_NAME_ALIAS(std::map< std::string COMMA  osg::ref_ptr< osgART::Field > >, osgART::FieldMap);

STD_MAP_REFLECTOR(std::map< std::string COMMA  osg::ref_ptr< osgART::Field > >);

