// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/PlaneARShadowRenderer>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgART::PlaneARShadowRenderer)
	I_BaseType(osgART::ShadowRenderer);
	I_ConstructorWithDefaults4(IN, osg::Node *, x, , IN, osg::MatrixTransform *, x, , IN, osg::Vec2f, size, , IN, int, markerId, 0);
	I_Method0(void, init);
END_REFLECTOR

