// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/GenericVideo>
#include <osgART/PluginManager>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(osgART::PluginManager)
	I_MethodWithDefaults2(void, load, IN, const std::string & , filename, "", IN, bool, resolveName, true);
	I_Method1(osg::Referenced*, get, IN, const std::string&, identifier);
	I_Method2(void, add, IN, const std::string&, name, IN, osg::Referenced*, plugin);
	I_StaticMethodWithDefaults1(osgART::PluginManager *, getInstance, IN, bool, erase, false );
END_REFLECTOR