// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/ShadowRenderer>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(osgART::ShadowRenderer)
	I_ConstructorWithDefaults3(IN, osg::Node *, x, , IN, osg::MatrixTransform *, x, , IN, int, markerId, 0);
	I_Constructor1(IN, const osgART::ShadowRenderer &, video);
	I_Method0(void, init);
	I_Method2(void, setShadowResolution, IN, int, width, IN, int, height);
END_REFLECTOR

