// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/GenericTracker>
#include <osgART/TrackerManager>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

// TYPE_NAME_ALIAS(osgART::GenericTracker *(*, osgART::TrackerManager::p_TrackerCreateFunc);

BEGIN_VALUE_REFLECTOR(osgART::TrackerManager)
	I_Method1(int, addTracker, IN, osgART::GenericTracker *, tracker);
	I_Method1(void, removeTracker, IN, osgART::GenericTracker *, tracker);
	I_Method1(osgART::GenericTracker *, getTracker, IN, int, idTracker);
	I_StaticMethod0(osgART::TrackerManager *, getInstance);
	I_StaticMethod0(void, destroy);
	I_StaticMethod1(osgART::GenericTracker *, createTrackerFromPlugin, IN, const std::string &, plugin);
END_REFLECTOR

