// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/VideoConfig>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(osgART::PixelFormatType)
	I_EnumLabel(osgART::VIDEOFORMAT_RGB555);
	I_EnumLabel(osgART::VIDEOFORMAT_RGB555);
	I_EnumLabel(osgART::VIDEOFORMAT_RGB565);
	I_EnumLabel(osgART::VIDEOFORMAT_RGB565);
	I_EnumLabel(osgART::VIDEOFORMAT_RGB24);
	I_EnumLabel(osgART::VIDEOFORMAT_RGB24);
	I_EnumLabel(osgART::VIDEOFORMAT_BGR24);
	I_EnumLabel(osgART::VIDEOFORMAT_BGR24);
	I_EnumLabel(osgART::VIDEOFORMAT_RGBA32);
	I_EnumLabel(osgART::VIDEOFORMAT_RGBA32);
	I_EnumLabel(osgART::VIDEOFORMAT_BGRA32);
	I_EnumLabel(osgART::VIDEOFORMAT_BGRA32);
	I_EnumLabel(osgART::VIDEOFORMAT_ARGB32);
	I_EnumLabel(osgART::VIDEOFORMAT_ARGB32);
	I_EnumLabel(osgART::VIDEOFORMAT_ABGR32);
	I_EnumLabel(osgART::VIDEOFORMAT_ABGR32);
	I_EnumLabel(osgART::VIDEOFORMAT_Y8);
	I_EnumLabel(osgART::VIDEOFORMAT_Y8);
	I_EnumLabel(osgART::VIDEOFORMAT_Y16);
	I_EnumLabel(osgART::VIDEOFORMAT_Y16);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV444);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV444);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV422);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV422);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV422P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV422P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV411);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV411);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV411P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV411P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV420P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV420P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV410P);
	I_EnumLabel(osgART::VIDEOFORMAT_YUV410P);
	I_EnumLabel(osgART::VIDEOFORMAT_GREY8);
	I_EnumLabel(osgART::VIDEOFORMAT_GREY8);
	I_EnumLabel(osgART::VIDEOFORMAT_MJPEG);
	I_EnumLabel(osgART::VIDEOFORMAT_MJPEG);
	I_EnumLabel(osgART::VIDEOFORMAT_ANY);
	I_EnumLabel(osgART::VIDEOFORMAT_ANY);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(osgART::FrameRateType)
	I_EnumLabel(osgART::VIDEOFRAMERATE_1_875);
	I_EnumLabel(osgART::VIDEOFRAMERATE_1_875);
	I_EnumLabel(osgART::VIDEOFRAMERATE_3_75);
	I_EnumLabel(osgART::VIDEOFRAMERATE_3_75);
	I_EnumLabel(osgART::VIDEOFRAMERATE_5);
	I_EnumLabel(osgART::VIDEOFRAMERATE_5);
	I_EnumLabel(osgART::VIDEOFRAMERATE_7_5);
	I_EnumLabel(osgART::VIDEOFRAMERATE_7_5);
	I_EnumLabel(osgART::VIDEOFRAMERATE_10);
	I_EnumLabel(osgART::VIDEOFRAMERATE_10);
	I_EnumLabel(osgART::VIDEOFRAMERATE_15);
	I_EnumLabel(osgART::VIDEOFRAMERATE_15);
	I_EnumLabel(osgART::VIDEOFRAMERATE_30);
	I_EnumLabel(osgART::VIDEOFRAMERATE_30);
	I_EnumLabel(osgART::VIDEOFRAMERATE_PAL);
	I_EnumLabel(osgART::VIDEOFRAMERATE_PAL);
	I_EnumLabel(osgART::VIDEOFRAMERATE_NTSC);
	I_EnumLabel(osgART::VIDEOFRAMERATE_NTSC);
	I_EnumLabel(osgART::VIDEOFRAMERATE_50);
	I_EnumLabel(osgART::VIDEOFRAMERATE_50);
	I_EnumLabel(osgART::VIDEOFRAMERATE_60);
	I_EnumLabel(osgART::VIDEOFRAMERATE_60);
	I_EnumLabel(osgART::VIDEOFRAMERATE_120);
	I_EnumLabel(osgART::VIDEOFRAMERATE_120);
	I_EnumLabel(osgART::VIDEOFRAMERATE_240);
	I_EnumLabel(osgART::VIDEOFRAMERATE_240);
	I_EnumLabel(osgART::VIDEOFRAMERATE_ANY);
	I_EnumLabel(osgART::VIDEOFRAMERATE_ANY);
	I_EnumLabel(osgART::VIDEOFRAMERATE_MAX);
	I_EnumLabel(osgART::VIDEOFRAMERATE_MAX);
END_REFLECTOR

