// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/VideoTextureRectangle>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(osgART::VideoTextureRectangle)
	I_Constructor1(IN, int, video);
	I_Constructor1(IN, int, video);
END_REFLECTOR

BEGIN_VALUE_REFLECTOR(osgART::VideoTextureRectangle)
	I_Constructor1(IN, int, video);
	I_Constructor1(IN, int, video);
END_REFLECTOR

