// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/VideoBackground>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgART::VideoBackground)
	I_BaseType(osgART::VideoLayer);
	I_BaseType(osgART::VideoLayer);
	I_ConstructorWithDefaults1(IN, int, videoId, 0);
	I_ConstructorWithDefaults1(IN, int, videoId, 0);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osgART::VideoBackground)
	I_BaseType(osgART::VideoLayer);
	I_BaseType(osgART::VideoLayer);
	I_ConstructorWithDefaults1(IN, int, videoId, 0);
	I_ConstructorWithDefaults1(IN, int, videoId, 0);
END_REFLECTOR

