// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/VideoPlaneMulti>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(osgART::VideoPlaneMulti)
	I_BaseType(osgART::GenericVideoObject);
	I_Constructor2(IN, int, width, IN, int, height);
	I_Method0(void, init);
	I_Method1(void, addVideo, IN, int, layerVideoID);
END_REFLECTOR

