// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osgART/VideoTexRectCallback>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(osgART::VideoTexRectCallback)
	I_Constructor3(IN, int, video, IN, int, vw, IN, int, vh);
	I_Method2(void, load, IN, const osg::TextureRectangle &, texture, IN, osg::State &, state);
	I_Method2(void, subload, IN, const osg::TextureRectangle &, texture, IN, osg::State &, state);
END_REFLECTOR

