// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <osg/CopyOp>
#include <osg/Geometry>
#include <osg/Image>
#include <osg/NodeVisitor>
#include <osg/Object>
#include <osgART/Calibration>
#include <osgART/VideoGeode>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_ENUM_REFLECTOR(osgART::VideoGeode::TextureMode)
	I_DeclaringFile("osgART/VideoGeode");
	I_EnumLabel(osgART::VideoGeode::USE_TEXTURE_2D);
	I_EnumLabel(osgART::VideoGeode::USE_TEXTURE_RECTANGLE);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(osgART::VideoGeode)
	I_DeclaringFile("osgART/VideoGeode");
	I_BaseType(osg::Geode);
	I_Constructor0(____VideoGeode,
	               "Constructor. ",
	               "");
	I_Constructor7(IN, osg::Image *, image, IN, osgART::Calibration *, calibration, IN, double, width, IN, double, height, IN, int, cols, IN, int, rows, IN, osgART::VideoGeode::TextureMode, textureMode,
	               ____VideoGeode__osg_Image_P1__osgART_Calibration_P1__double__double__int__int__TextureMode,
	               "",
	               "");
	I_ConstructorWithDefaults2(IN, const osgART::VideoGeode &, x, , IN, const osg::CopyOp &, copyop, osg::CopyOp::SHALLOW_COPY,
	                           ____VideoGeode__C5_VideoGeode_R1__C5_osg_CopyOp_R1,
	                           "Copy constructor using CopyOp to manage deep vs shallow copy. ",
	                           "");
	I_Method0(osg::Object *, cloneType,
	          Properties::VIRTUAL,
	          __osg_Object_P1__cloneType,
	          "clone an object of the same type as the node. ",
	          "");
	I_Method1(osg::Object *, clone, IN, const osg::CopyOp &, copyop,
	          Properties::VIRTUAL,
	          __osg_Object_P1__clone__C5_osg_CopyOp_R1,
	          "return a clone of a node, with Object* return type. ",
	          "");
	I_Method1(bool, isSameKindAs, IN, const osg::Object *, obj,
	          Properties::VIRTUAL,
	          __bool__isSameKindAs__C5_osg_Object_P1,
	          "return true if this and obj are of the same kind of object. ",
	          "");
	I_Method0(const char *, className,
	          Properties::VIRTUAL,
	          __C5_char_P1__className,
	          "return the name of the node's class type. ",
	          "");
	I_Method0(const char *, libraryName,
	          Properties::VIRTUAL,
	          __C5_char_P1__libraryName,
	          "return the name of the node's library. ",
	          "");
	I_Method1(void, accept, IN, osg::NodeVisitor &, nv,
	          Properties::VIRTUAL,
	          __void__accept__osg_NodeVisitor_R1,
	          "Visitor Pattern : calls the apply method of a NodeVisitor with this node's type. ",
	          "");
	I_StaticMethodWithDefaults7(osg::Geometry *, createVideoMesh, IN, osg::Image *, image, , IN, osgART::Calibration *, calibration, NULL, IN, double, width, 1.0, IN, double, height, 1.0, IN, int, cols, 20, IN, int, rows, 20, IN, osgART::VideoGeode::TextureMode, textureMode, osgART::VideoGeode::USE_TEXTURE_2D,
	                            __osg_Geometry_P1__createVideoMesh__osg_Image_P1__osgART_Calibration_P1__double__double__int__int__TextureMode_S,
	                            "",
	                            "");
END_REFLECTOR

